version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./server/.env
    volumes:
      - ./server/data/audio_data:/app/data/audio_data
      - ./server/data/database.db:/app/data/database.db

networks:
  app-network:
    driver: bridge
