version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  backend:
    deploy:
      resources:
        limits:
          memory: 1g
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./server/.env
    volumes:
      - ./server/data:/app/data

networks:
  app-network:
    driver: bridge
